image: maven:3.8.1-openjdk-17-slim

pipelines:
  custom:
    deploy-to-artifactory-dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
            - mvn -s settings.xml clean install deploy
