image: public.ecr.aws/a1t5b6y5/ndm/java17-maven-base:latest

pipelines:
  custom:
    deploy-to-artifactory-dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -s settings.xml clean install deploy
    build-credit-micro-service-container:
      - step:
          name: Build and deploy
          caches:
            - maven
          services:
            - docker
          script:
            - cd credit-micro-service
            - mvn -s ../settings.xml clean install -Dpmd.skip=true -Dmaven.test.skip=true
            - IMAGE="ndm/credit-micro-service"
            - TAG=${BITBUCKET_BUILD_NUMBER}.${BITBUCKET_COMMIT}
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${AWS_TEST_BASE_URL}
            - docker build -f src/main/docker/Dockerfile.jvm -t ${IMAGE}:${TAG} .
            - docker tag ${IMAGE}:${TAG} ${AWS_TEST_BASE_URL}/${IMAGE}:${TAG}
            - docker push ${AWS_TEST_BASE_URL}/${IMAGE}:${TAG}
