image: public.ecr.aws/a1t5b6y5/ndm/java17-maven-base:latest

pipelines:
  custom:
    deploy-to-artifactory-dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -s settings.xml clean install deploy
