image: 043970611749.dkr.ecr.eu-west-1.amazonaws.com/ndm/java17-maven-base:latest

pipelines:
  custom:
    deploy-to-artifactory-dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -s settings.xml clean install deploy
