image: maven:3.8.1-openjdk-17-slim

pipelines:
  custom:
    deploy-to-fargate-dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install