---
version: '3.9'

networks:
  app_network:
    driver: bridge

services:
  newman:
    image: registry.gitlab.com/hamedhatami/quarkus-demo/newman:1.0.0
    container_name: postmanTests
    command: run quarkus_demo_collection.json  --reporters cli,html  --reporter-html-export report.html
    volumes:
      - ./collections:/etc/newman
    depends_on:
      - api
    networks:
      - app_network
  api:
    image: registry.gitlab.com/hamedhatami/quarkus-demo:1.0.0
    container_name: quarkus_demo
    ports:
      - "8080:8080"
    networks:
      - app_network