FROM maven:3.8.6-openjdk-11-slim

# Install unzip
RUN apt-get update \
 && apt-get install wget unzip zip -y

# Install aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

ENTRYPOINT ["/bin/sh", "-c"]
