FROM maven:3.8.5-openjdk-17

# Install unzip
RUN microdnf install zip unzip -y

# Install aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

ENTRYPOINT ["/bin/sh", "-c"]
