FROM vegardit/graalvm-maven:22.3.1-java17

# Install unzip
RUN apt-get update && apt-get install -y --no-install-recommends zip unzip

# Install aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

ENTRYPOINT ["/bin/sh", "-c"]
