---
apiVersion: v1
kind: Service
metadata:
  name: {{include "quarkus-demo.fullname" .}}
  namespace: {{.Values.app.namespace}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  selector:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.Version}}
  type: {{.Values.service.type}}
